### ISSUE TITLE
Exception on loading/creating map

### ISSUE THREAD

**Issue by UnFamousSoul** [DeadlyMC/ProtoSky#21]
Got this on crash report:
<details>
  <summary>Click me</summary>
  
  Description: Exception initializing level
  
  java.lang.NoClassDefFoundError: net/minecraft/class_7924
	  at protosky.stuctures.StructureHelper.handleStructures(StructureHelper.java:358)
	  at net.minecraft.class_2806.handler$caf000$FEATURES(class_2806.java:559)
	  at net.minecraft.class_2806.method_20613(class_2806.java)
	  at net.minecraft.class_2806.method_12154(class_2806.java:292)
	  at net.minecraft.class_3898.method_17225(class_3898.java:679)
	  at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	  at net.minecraft.class_3898.method_17224(class_3898.java:673)
	  at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	  at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	  at net.minecraft.class_3900.method_17634(class_3900.java:62)
	  at net.minecraft.class_3846.method_16907(class_3846.java:91)
	  at net.minecraft.class_3846.method_16900(class_3846.java:146)
	  at net.minecraft.class_3846.run(class_3846.java:102)
	  at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	  at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	  at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	  at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	  at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	  at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
  Caused by: java.lang.ClassNotFoundException: net.minecraft.class_7924
	  ... 19 more
  
  
  A detailed walkthrough of the error, its code path and all known details is as follows:
  ---------------------------------------------------------------------------------------
  
  -- Head --
  Thread: Server thread
  Stacktrace:
	  at protosky.stuctures.StructureHelper.handleStructures(StructureHelper.java:358)
	  at net.minecraft.class_2806.handler$caf000$FEATURES(class_2806.java:559)
	  at net.minecraft.class_2806.method_20613(class_2806.java)
	  at net.minecraft.class_2806.method_12154(class_2806.java:292)
	  at net.minecraft.class_3898.method_17225(class_3898.java:679)
	  at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	  at net.minecraft.class_3898.method_17224(class_3898.java:673)
	  at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	  at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	  at net.minecraft.class_3900.method_17634(class_3900.java:62)
	  at net.minecraft.class_3846.method_16907(class_3846.java:91)
	  at net.minecraft.class_3846.method_16900(class_3846.java:146)
	  at net.minecraft.class_3846.run(class_3846.java:102)
  
  -- Affected level --
  Details:
	  All players: 0 total; []
	  Chunk stats: 625
	  Level dimension: minecraft:overworld
	  Level spawn location: World: (168,64,-168), Section: (at 8,0,8 in 10,4,-11; chunk contains blocks 160,-64,-176 to 175,319,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	  Level time: 0 game time, 0 day time
	  Level name: Skyblock
	  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	  Known server brands: fabric
	  Level was modded: true
	  Level storage version: 0x04ABD - Anvil
  Stacktrace:
	  at net.minecraft.server.MinecraftServer.method_3786(MinecraftServer.java:367)
	  at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:315)
	  at net.minecraft.class_1132.method_3823(class_1132.java:68)
	  at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636)
	  at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	  at java.base/java.lang.Thread.run(Thread.java:833)
  
  -- System Details --
  Details:
	  Minecraft Version: 1.19.3
	  Minecraft Version ID: 1.19.3
	  Operating System: Windows 10 (amd64) version 10.0
	  Java Version: 17.0.3, Microsoft
	  Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	  Memory: 1622546720 bytes (1547 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	  CPUs: 12
	  Processor Vendor: GenuineIntel
	  Processor Name: Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz
	  Identifier: Intel64 Family 6 Model 62 Stepping 4
	  Microarchitecture: Ivy Bridge (Server)
	  Frequency (GHz): 2.10
	  Number of physical packages: 1
	  Number of physical CPUs: 6
	  Number of logical CPUs: 12
	  Graphics card #0 name: NVIDIA GeForce 9500 GT
	  Graphics card #0 vendor: NVIDIA (0x10de)
	  Graphics card #0 VRAM (MB): 1024.00
	  Graphics card #0 deviceId: 0x0640
	  Graphics card #0 versionInfo: DriverVersion=21.21.13.4201
	  Memory slot #0 capacity (MB): 2048.00
	  Memory slot #0 clockSpeed (GHz): 1.60
	  Memory slot #0 type: DDR3
	  Memory slot #1 capacity (MB): 8192.00
	  Memory slot #1 clockSpeed (GHz): 1.60
	  Memory slot #1 type: DDR3
	  Memory slot #2 capacity (MB): 2048.00
	  Memory slot #2 clockSpeed (GHz): 1.60
	  Memory slot #2 type: DDR3
	  Memory slot #3 capacity (MB): 8192.00
	  Memory slot #3 clockSpeed (GHz): 1.60
	  Memory slot #3 type: DDR3
	  Virtual memory max (MB): 28658.52
	  Virtual memory used (MB): 13300.88
	  Swap memory total (MB): 8192.00
	  Swap memory used (MB): 263.93
	  JVM Flags: 13 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -Xms2048M -Xmx2048M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M
</details>

**Comment by polarbub** [comment]
Can you reproduce it? If so, how?
